# Secret scanning local mirror (row 21) — complements GitHub-native secret scanning + push protection
# (enabled on the repo). Uses the gitleaks CLI directly for reliability. SHA-pinned.
name: gitleaks
on:
  push: {}
  pull_request: {}
permissions:
  contents: read
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: taiki-e/install-action@15449e3094499af05d8d964a1c884208e4b8b595 # v2.81.11
        with:
          tool: gitleaks
      - run: gitleaks detect --source . --redact --no-banner --verbose --exit-code 1
